create view ayudas as select sa_socialaid_id, sa_name, count(*) as total from gavius group by sa_socialaid_id, sa_name;
create view poblacion as SELECT DATE_TRUNC('year',birthdate) AS anyo, COUNT(*) AS total FROM cens GROUP BY DATE_TRUNC('year',birthdate);
CREATE VIEW renoven AS SELECT gaviususer_id, DATE_TRUNC('year',daterequested) AS anyo, sa_socialaid_id FROM gavius WHERE status = 'Approved';
CREATE INDEX idx_renoven_socialaid ON gavius(sa_socialaid_id);
CREATE INDEX idx_renoven_daterequested ON gavius(daterequested);
update cens set agerange = 1;
update cens set agerange = 2 where extract(years from age(birthdate)) > 30;
update cens set agerange = 3 where extract(years from age(birthdate)) > 45;
update cens set agerange = 4 where extract(years from age(birthdate)) > 60;
create index if not exists idx_cens_sexe on cens(ge_name);
create index if not exists idx_cens_barri on cens(gu_da_0_n_name);
create index if not exists idx_cens_edat on cens(agerange);
create table if not exists bolas(sa_id_ini  integer not null, sa_id_next integer not null, count integer default 0, constraint bolas_pk primary key (sa_id_next, sa_id_ini));
create table if not exists caminos(id SERIAL, source integer not null, target integer not null, mainstat decimal not null, constraint caminos_pk primary key(source,target));
DELETE FROM bolas;
DELETE FROM caminos;
ALTER SEQUENCE caminos_id_seq RESTART WITH 1;
UPDATE prediccio SET mean_ci_lower = 0 WHERE mean_ci_lower < 0;
UPDATE gavius SET sa_name = 'ExclusioResidencial' WHERE sa_socialaid_id = 1;
UPDATE gavius SET sa_name = 'SolAliments' WHERE sa_socialaid_id = 2;
UPDATE gavius SET sa_name = 'Carnet Blau' WHERE sa_socialaid_id = 3;
UPDATE gavius SET sa_name = 'AjutIBINombrosa' WHERE sa_socialaid_id = 4;
UPDATE gavius SET sa_name = 'Teleassistencia' WHERE sa_socialaid_id = 5;
UPDATE gavius SET sa_name = 'BecaEscolaBressol' WHERE sa_socialaid_id = 6;
UPDATE gavius SET sa_name = 'Subvencio' WHERE sa_socialaid_id = 7;
UPDATE gavius SET sa_name = 'AjutIBIMonoparental' WHERE sa_socialaid_id = 8;
UPDATE gavius SET sa_name = 'ConsultaDades' WHERE sa_socialaid_id = 9;
UPDATE gavius SET sa_name = 'BecaMenjador' WHERE sa_socialaid_id = 10;
UPDATE gavius SET sa_name = 'BorsaTreball' WHERE sa_socialaid_id = 11;
UPDATE gavius SET sa_name = 'MeritsRequisits' WHERE sa_socialaid_id = 12;
UPDATE gavius SET sa_name = 'IBI: obres estalvi energètic' WHERE sa_socialaid_id = 13;
UPDATE gavius SET sa_name = 'IBI: Protecció Oficial' WHERE sa_socialaid_id = 14;
UPDATE gavius SET sa_name = 'Habitatge' WHERE sa_socialaid_id = 15;
UPDATE gavius SET sa_name = 'Residus municipals' WHERE sa_socialaid_id = 16;
UPDATE gavius SET sa_name = 'Benestar Social' WHERE sa_socialaid_id = 17;
UPDATE gavius SET sa_name = 'Aparcament mobilitat reduïda' WHERE sa_socialaid_id = 18;
UPDATE gavius SET sa_name = 'Atenció social bàsica' WHERE sa_socialaid_id = 19;
UPDATE gavius SET sa_name = 'Urgència social' WHERE sa_socialaid_id = 20;