{
 "title": "Perfil Sociodemografic",
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ayuda",
    "label": "Ajuda",
    "query": "select distinct sa_name from gavius"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "    <script src=\"http://code.jquery.com/jquery-2.1.4.min.js\"></script>\n<script>\n    $(function(){\n        $('a').each(function(){\n            if ($(this).prop('href') == window.location.href) {\n                $(this).addClass('active'); $(this).addClass('active');\n            }\n        });\n    });\n</script>\n\n<style>\n    .navbar {\n        overflow: hidden;\n        background-color: #116ACC;\n        font-family: Arial, Helvetica, sans-serif;\n    }\n\n    .navbar a {\n        float: left;\n        font-size: 18px;\n        color: white;\n        text-align: center;\n        padding: 8px 12px;\n        text-decoration: none;\n    }\n\n    .navbar a:hover {\n        color: white;\n        text-decoration: underline;\n    }\n\n    /*.navbar .active{\n        color:            white;\n        background-color: #4f81bd;\n    }*/\n\n</style>\n\n<div class=\"navbar\">\n    <a href=\"/d/kEtG3wD4z/estat-de-les-tramitacions?orgId=1\">Estat de les tramitacions</a>\n    <a href=\"/d/EJrGvUcVk/perfil-sociodemografic?orgId=1\">Perfil sociodemogràfic</a>\n    <a href=\"/d/0PwjJe5Vz/camins-probables?orgId=1\">Camins probables</a>\n    <a href=\"/d/lU48FST4z/diagnosi-social?orgId=1\">Diagnosi social</a>\n    <a href=\"/d/3cwNQQ14z/detall-dels-grups-comorbid?orgId=1\">Detall dels grups Comòrbids</a>\n    <a href=\"/d/nBXKCKA4k/cronicitat?orgId=1\">Cronicitat</a>\n    <a>|</a>\n    <a href=\"/d/Ij-VuwJVk/prediccio-de-levolucio-temporal-dajudes?orgId=1\">Prognosi</a>\n    <a>|</a>\n    <a href=\"/d/0zQpdUAVz/assignacio-de-pressupost?orgId=1\">Projecció</a>\n</div>"
   }
  },
  {
   "title": "Gràfic d'embut",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Població\" FROM cens where birthdate < $__timeTo() "
    },
    {
     "rawSql": "SELECT count(*) AS \"Peticionàries\"\nFROM gavius INNER JOIN cens ON gavius.gaviususer_id = cens.gaviususer_id\nwhere  $__timeFilter(daterequested) AND sa_name IN (${ayuda})"
    },
    {
     "rawSql": "SELECT count(*) AS \"Peticionàries\"\nFROM gavius INNER JOIN cens ON gavius.gaviususer_id = cens.gaviususer_id\nwhere  $__timeFilter(daterequested) AND gavius.status = 'Approved' AND sa_name IN (${ayuda})"
    }
   ]
  },
  {
   "title": "Distribució",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  case when agerange=1 then '18-30' when agerange=2 then '30-45' when agerange=3 then '45-60' else '+60' end as rang_edat,\n  (select count(*) from cens where agerange = padre.agerange and birthdate < $__timeFrom()) as Població,\n  (select count(*) from gavius inner join cens on gavius.gaviususer_id = cens.gaviususer_id where agerange = padre.agerange and sa_name in (${ayuda}) and $__timeFilter(daterequested)) as Peticionàries,\n  (select count(*) from gavius inner join cens ON gavius.gaviususer_id = cens.gaviususer_id where agerange = padre.agerange and sa_name in (${ayuda}) and gavius.status = 'Approved' and $__timeFilter(daterequested)) as Beneficiàries\nFROM cens as padre\nGROUP BY agerange\nORDER BY agerange\n\n"
    }
   ]
  },
  {
   "title": "Evolució temporal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('YEAR',daterequested) AS \"time\",\r\n  count(*) AS \"Beneficiàries\"\r\nFROM gavius\r\nWHERE status = 'Approved' AND sa_name IN (${ayuda}) and daterequested >=  date_trunc('YEAR',to_timestamp( ${__from:YYYY-MM-DD}/1000)::date)\r\nGROUP BY date_trunc('YEAR',daterequested)"
    },
    {
     "rawSql": "SELECT\r\n  date_trunc('YEAR',daterequested) AS \"time\",\r\n  count(*) AS \"Peticionaries\"\r\nFROM gavius\r\nWHERE sa_name IN (${ayuda}) and daterequested >=  date_trunc('YEAR',to_timestamp( ${__from:YYYY-MM-DD}/1000)::date)\r\nGROUP BY date_trunc('YEAR',daterequested)"
    },
    {
     "rawSql": "select anyo, (SELECT sum(total) FROM poblacion where anyo < padre.anyo) as Poblacio\nfrom poblacion as padre\nWHERE  anyo >=  date_trunc('YEAR',to_timestamp( ${__from:YYYY-MM-DD}/1000)::date)"
    }
   ]
  }
 ]
}