{
 "title": "Visualització dels resultats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "    <script src=\"http://code.jquery.com/jquery-2.1.4.min.js\"></script>\n<script>\n    $(function(){\n        $('a').each(function(){\n            if ($(this).prop('href') == window.location.href) {\n                $(this).addClass('active'); $(this).addClass('active');\n            }\n        });\n    });\n</script>\n\n<style>\n    .navbar {\n        overflow: hidden;\n        background-color: #116ACC;\n        font-family: Arial, Helvetica, sans-serif;\n    }\n\n    .navbar a {\n        float: left;\n        font-size: 18px;\n        color: white;\n        text-align: center;\n        padding: 8px 10px;\n        text-decoration: none;\n    }\n\n    .navbar a:hover {\n        color: white;\n        text-decoration: underline;\n    }\n\n    .navbar .active{\n        font-weight: bold;\n    }\n\n</style>\n\n<div class=\"navbar\">\n    <a href=\"/d/kEtG3wD4z/estat-de-les-tramitacions?orgId=1\">Diagnosi</a>\n    <a>|</a>    \n    <a href=\"/d/Ij-VuwJVk/prediccio-de-levolucio-temporal-dajudes?orgId=1\">Prognosi</a>\n    <a>|</a>\n    <a href=\"d/0oDR83J4k/seleccio-parametres-dentrada?orgId=1\">Selecció paràmetres d'entrada</a>    \n    <a href=\"/d/Iwi9480Vk/visualitzacio-dels-resultats?orgId=1\">Assignació de pressupost</a>\n</div>"
   }
  },
  {
   "title": "Imports vs concessions",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SELECT sa_name FROM ayudas WHERE sa_socialaid_id = budgets.id) AS \"Ajuda\",\r\n  budget,\r\n  assigned\r\nFROM\r\n  budgets\r\nWHERE\r\n  type = 'suggested' AND assigned != 0\r\nORDER BY id"
    }
   ]
  },
  {
   "title": "Cobertura",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SELECT sa_name FROM ayudas WHERE sa_socialaid_id = s.id) AS \"Ajuda\",\r\n  assigned AS \"Beneficiaris coberts\",\r\n  s.budget / (SELECT i.budget FROM budgets i WHERE i.id = s.id AND i.type = 'ideal') AS \"Cobertura\"\r\n\r\nFROM\r\n  budgets s\r\nWHERE type = 'suggested'"
    }
   ]
  },
  {
   "title": "Cost per concessió (€)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SELECT sa_name FROM ayudas WHERE sa_socialaid_id = s.id) AS \"Ajuda\",\r\n  cost_assignment\r\nFROM \r\n  budget_metrics_costs s\r\nWHERE \r\n  s.cost_assignment != 0\r\nORDER BY id;"
    }
   ]
  },
  {
   "title": "Cost per habitant (€)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SELECT sa_name FROM ayudas WHERE sa_socialaid_id = s.id) AS \"Ajuda\",\r\n  cost_inhabitant\r\nFROM \r\n  budget_metrics_costs s\r\nWHERE \r\n  s.cost_assignment != 0\r\nORDER BY id;"
    }
   ]
  }
 ]
}