{
 "title": "Diagnosi social",
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "comorbid",
    "label": "Grup de comorbiditat",
    "query": "SELECT distinct COALESCE (cggu_cg_name, 'No perfil recurs SSB') FROM cens"
   },
   {
    "name": "sexe",
    "label": "Sexe",
    "query": "select distinct ge_name from cens where not ge_name is null"
   },
   {
    "name": "edat",
    "label": "Grup d'edat",
    "query": "18-30 : 1,30-45 : 2,45-60 : 3,60+ : 4"
   },
   {
    "name": "barri",
    "label": "Barri",
    "query": "SELECT gu_da_0_n_name FROM cens WHERE gu_da_0_n_name != 'Barri desconegut' GROUP BY gu_da_0_n_name;"
   },
   {
    "name": "cens",
    "label": "Secció censal",
    "query": "SELECT gu_da_0_censustract FROM cens WHERE gu_da_0_censustract IS NOT NULL AND gu_da_0_n_name IN(${barri}) GROUP BY gu_da_0_censustract ORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "    <script src=\"http://code.jquery.com/jquery-2.1.4.min.js\"></script>\n<script>\n    $(function(){\n        $('a').each(function(){\n            if ($(this).prop('href') == window.location.href) {\n                $(this).addClass('active'); $(this).addClass('active');\n            }\n        });\n    });\n</script>\n\n<style>\n    .navbar {\n        overflow: hidden;\n        background-color: #116ACC;\n        font-family: Arial, Helvetica, sans-serif;\n    }\n\n    .navbar a {\n        float: left;\n        font-size: 18px;\n        color: white;\n        text-align: center;\n        padding: 8px 12px;\n        text-decoration: none;\n    }\n\n    .navbar a:hover {\n        color: white;\n        text-decoration: underline;\n    }\n\n    /*.navbar .active{\n        color:            white;\n        background-color: #4f81bd;\n    }*/\n\n</style>\n\n<div class=\"navbar\">\n    <a href=\"/d/kEtG3wD4z/estat-de-les-tramitacions?orgId=1\">Estat de les tramitacions</a>\n    <a href=\"/d/EJrGvUcVk/perfil-sociodemografic?orgId=1\">Perfil sociodemogràfic</a>\n    <a href=\"/d/0PwjJe5Vz/camins-probables?orgId=1\">Camins probables</a>\n    <a href=\"/d/lU48FST4z/diagnosi-social?orgId=1\">Diagnosi social</a>\n</div>"
   }
  },
  {
   "title": "Diagnosi social",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  gu_da_0_municipality_name AS \"Municipi\",\r\n  gu_da_0_n_name AS \"Barri\",\r\n  count(*) AS \"Població\",\r\n  barris.lat,\r\n  barris.lon\r\nFROM\r\ncens LEFT JOIN barris ON cens.gu_da_0_n_name = barris.name\r\nWHERE \r\n  (ge_name IN (${sexe}))\r\n  AND (COALESCE (cggu_cg_name, 'No perfil recurs SSB')  IN (${comorbid}))\r\n  AND (agerange IN (${edat}))\r\nGROUP BY gu_da_0_n_name, gu_da_0_municipality_name, barris.lat, barris.lon\r\nORDER BY 2;"
    }
   ]
  },
  {
   "title": "Grup Comòrbid",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nCOALESCE (cggu_cg_name, 'No perfil recurs SSB') , count(*)\r\nFROM\r\ncens\r\nWHERE \r\n  cggu_cg_name IS NOT NULL\r\n  AND (gu_da_0_n_name IN (${barri}))\r\n  AND (gu_da_0_censustract IN (${cens}))\r\nGROUP BY cggu_cg_name\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Orígen del diagnòstic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nCOALESCE (CAST(cggu_origin AS TEXT), 'Sense orígen' ) ,count(*)\r\nFROM\r\ncens\r\nWHERE \r\n  (gu_da_0_n_name IN (${barri}))\r\n  AND (gu_da_0_censustract IN (${cens}))\r\nGROUP BY cggu_origin;"
    }
   ]
  }
 ]
}