{
 "title": "Perfil Sociodemografic",
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ayuda",
    "query": "select distinct sa_name from gavius"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "    <script src=\"http://code.jquery.com/jquery-2.1.4.min.js\"></script>\n<script>\n    $(function(){\n        $('a').each(function(){\n            if ($(this).prop('href') == window.location.href) {\n                $(this).addClass('active'); $(this).addClass('active');\n            }\n        });\n    });\n</script>\n\n<style>\n    .navbar {\n        overflow: hidden;\n        background-color: #083566;\n        font-family: Arial, Helvetica, sans-serif;\n    }\n\n    .navbar a {\n        float: left;\n        font-size: 18px;\n        color: white;\n        text-align: center;\n        padding: 8px 12px;\n        text-decoration: none;\n    }\n\n    .navbar a:hover {\n        color: white;\n        text-decoration: underline;\n    }\n\n    .navbar .active{\n        color:            white;\n        background-color: #4f81bd;\n    }\n\n</style>\n\n<div class=\"navbar\">\n    <a href=\"/\">Estat de les tramitacions</a>\n    <a href=\"#\">Perfil sociodemogràfic</a>\n    <a href=\"/d/0PwjJe5Vz/dashboard-3?orgId=1\">Camins probables</a>\n</div>"
   }
  },
  {
   "title": "Distribució",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Població\"\nFROM cens\nGROUP BY agerange"
    },
    {
     "rawSql": "SELECT count(*) AS \"Peticionàries\"\nFROM gavius INNER JOIN cens ON gavius.gaviususer_id = cens.gaviususer_id\nwhere gavius.status IS NOT NULL GROUP BY cens.agerange"
    },
    {
     "rawSql": "SELECT count(*) AS \"Beneficiàries\"\nFROM gavius INNER JOIN cens ON gavius.gaviususer_id = cens.gaviususer_id\nwhere gavius.status = 'Approved' GROUP BY cens.agerange"
    }
   ]
  },
  {
   "title": "Gràfic d'embut",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS \"Població\"\nFROM cens"
    },
    {
     "rawSql": "SELECT\n  count(*) AS \"Peticionàries\"\nFROM (gavius\n     JOIN cens ON ((gavius.gaviususer_id = CAST(cens.gaviususer_id AS bigint))))\nwhere gavius.status IS NOT NULL AND gavius.socialaid_socialaid_id IN (${ajuda})"
    },
    {
     "rawSql": "SELECT\n  count(*) AS \"Beneficiàries\"\nFROM (gavius\n     JOIN cens ON ((gavius.gaviususer_id = CAST(cens.gaviususer_id AS bigint))))\nwhere gavius.status = 'Approved' AND gavius.socialaid_socialaid_id IN (${ajuda})"
    }
   ]
  },
  {
   "title": "Evolució temporal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \ntime,\n(SELECT sum(gent) FROM població t WHERE t.time <= p.time) AS \"Habitants\"\nFROM població p\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date_trunc('YEAR',daterequested) AS \"time\",\n  count(*) AS \"Peticionàries\"\nFROM gavius\nWHERE status IS NOT NULL AND gavius.socialaid_socialaid_id IN (${ajuda})\nGROUP BY date_trunc('YEAR',daterequested)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date_trunc('YEAR',daterequested) AS \"time\",\n  count(*) AS \"Beneficiàries\"\nFROM gavius\nWHERE status = 'Approved' AND gavius.socialaid_socialaid_id IN (${ajuda})\nGROUP BY date_trunc('YEAR',daterequested)\nORDER BY 1"
    }
   ]
  }
 ]
}