apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: "12345678"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      postgresVersion: 1500
      timescaledb: false